import { getEnumValues } from '@gamepark/rules-api';

export enum NumberCard {
  NumberCard1 = 1,
  NumberCard2,
  NumberCard3,
  NumberCard4,
  NumberCard5,
  NumberCard6,
  NumberCard7,
  NumberCard8,
  NumberCard9,
  NumberCard10,
  NumberCard11,
  NumberCard12,
  NumberCard13,
  NumberCard14,
  NumberCard15,
  NumberCard16,
  NumberCard17,
  NumberCard18,
  NumberCard19,
  NumberCard20,
  NumberCard21,
  NumberCard22,
  NumberCard23,
  NumberCard24,
  NumberCard25,
  NumberCard26,
  NumberCard27,
  NumberCard28,
  NumberCard29,
  NumberCard30,
  NumberCard31,
  NumberCard32,
  NumberCard33,
  NumberCard34,
  NumberCard35,
  NumberCard36,
  NumberCard37,
  NumberCard38,
  NumberCard39,
  NumberCard40,
  NumberCard41,
  NumberCard42,
  NumberCard43,
  NumberCard44,
  NumberCard45,
  NumberCard46,
  NumberCard47,
  NumberCard48,
  NumberCard49,
  NumberCard50,
  NumberCard51,
  NumberCard52,
  NumberCard53,
  NumberCard54,
  NumberCard55,
  NumberCard56,
  NumberCard57,
  NumberCard58,
  NumberCard59,
  NumberCard60,
  NumberCard61,
  NumberCard62,
  NumberCard63,
  NumberCard64,
  NumberCard65,
  NumberCard66,
  NumberCard67,
  NumberCard68,
  NumberCard69,
  NumberCard70,
  NumberCard71,
  NumberCard72,
  NumberCard73,
  NumberCard74,
  NumberCard75,
  NumberCard76,
  NumberCard77,
  NumberCard78,
  NumberCard79,
  NumberCard80,
  NumberCard81,
  NumberCard82,
  NumberCard83,
  NumberCard84,
  NumberCard85,
  NumberCard86,
  NumberCard87,
  NumberCard88,
  NumberCard89,
  NumberCard90,
  TopStar = 200
}

export const numberCards = getEnumValues(NumberCard).filter(id => id !== NumberCard.TopStar)

export function isTopStar(id: NumberCard | undefined): boolean {
  return id === NumberCard.TopStar
}

export type NumericCard = Exclude<NumberCard, NumberCard.TopStar>

export enum Colors {
  Pink = 1,
  Yellow,
  Green,
  Cyan,
  Orange
}

interface Data {
  color: Colors,
  number: number,
  stars: number
}

export const numberCardData: Record<NumericCard, Data> = {
  [NumberCard.NumberCard1]: { color: Colors.Pink, number: 1, stars: 0 },
  [NumberCard.NumberCard2]: { color: Colors.Yellow, number: 2, stars: 0 },
  [NumberCard.NumberCard3]: { color: Colors.Green, number: 3, stars: 0 },
  [NumberCard.NumberCard4]: { color: Colors.Cyan, number: 4, stars: 0 },
  [NumberCard.NumberCard5]: { color: Colors.Orange, number: 5, stars: 0 },
  [NumberCard.NumberCard6]: { color: Colors.Pink, number: 6, stars: 1 },
  [NumberCard.NumberCard7]: { color: Colors.Yellow, number: 7, stars: 1 },
  [NumberCard.NumberCard8]: { color: Colors.Green, number: 8, stars: 1 },
  [NumberCard.NumberCard9]: { color: Colors.Cyan, number: 9, stars: 1 },
  [NumberCard.NumberCard10]: { color: Colors.Orange, number: 10, stars: 1 },
  [NumberCard.NumberCard11]: { color: Colors.Pink, number: 11, stars: 0 },
  [NumberCard.NumberCard12]: { color: Colors.Yellow, number: 12, stars: 0 },
  [NumberCard.NumberCard13]: { color: Colors.Green, number: 13, stars: 0 },
  [NumberCard.NumberCard14]: { color: Colors.Cyan, number: 14, stars: 0 },
  [NumberCard.NumberCard15]: { color: Colors.Orange, number: 15, stars: 0 },
  [NumberCard.NumberCard16]: { color: Colors.Pink, number: 16, stars: 2 },
  [NumberCard.NumberCard17]: { color: Colors.Yellow, number: 17, stars: 2 },
  [NumberCard.NumberCard18]: { color: Colors.Green, number: 18, stars: 2 },
  [NumberCard.NumberCard19]: { color: Colors.Cyan, number: 19, stars: 2 },
  [NumberCard.NumberCard20]: { color: Colors.Orange, number: 20, stars: 2 },
  [NumberCard.NumberCard21]: { color: Colors.Pink, number: 21, stars: 0 },
  [NumberCard.NumberCard22]: { color: Colors.Yellow, number: 22, stars: 0 },
  [NumberCard.NumberCard23]: { color: Colors.Green, number: 23, stars: 0 },
  [NumberCard.NumberCard24]: { color: Colors.Cyan, number: 24, stars: 0 },
  [NumberCard.NumberCard25]: { color: Colors.Orange, number: 25, stars: 0 },
  [NumberCard.NumberCard26]: { color: Colors.Pink, number: 26, stars: 1 },
  [NumberCard.NumberCard27]: { color: Colors.Yellow, number: 27, stars: 1 },
  [NumberCard.NumberCard28]: { color: Colors.Green, number: 28, stars: 1 },
  [NumberCard.NumberCard29]: { color: Colors.Cyan, number: 29, stars: 1 },
  [NumberCard.NumberCard30]: { color: Colors.Orange, number: 30, stars: 1 },
  [NumberCard.NumberCard31]: { color: Colors.Pink, number: 31, stars: 0 },
  [NumberCard.NumberCard32]: { color: Colors.Yellow, number: 32, stars: 0 },
  [NumberCard.NumberCard33]: { color: Colors.Green, number: 33, stars: 0 },
  [NumberCard.NumberCard34]: { color: Colors.Cyan, number: 34, stars: 0 },
  [NumberCard.NumberCard35]: { color: Colors.Orange, number: 35, stars: 0 },
  [NumberCard.NumberCard36]: { color: Colors.Pink, number: 36, stars: 2 },
  [NumberCard.NumberCard37]: { color: Colors.Yellow, number: 37, stars: 2 },
  [NumberCard.NumberCard38]: { color: Colors.Green, number: 38, stars: 2 },
  [NumberCard.NumberCard39]: { color: Colors.Cyan, number: 39, stars: 2 },
  [NumberCard.NumberCard40]: { color: Colors.Orange, number: 40, stars: 2 },
  [NumberCard.NumberCard41]: { color: Colors.Pink, number: 41, stars: 0 },
  [NumberCard.NumberCard42]: { color: Colors.Yellow, number: 42, stars: 0 },
  [NumberCard.NumberCard43]: { color: Colors.Green, number: 43, stars: 0 },
  [NumberCard.NumberCard44]: { color: Colors.Cyan, number: 44, stars: 0 },
  [NumberCard.NumberCard45]: { color: Colors.Orange, number: 45, stars: 0 },
  [NumberCard.NumberCard46]: { color: Colors.Pink, number: 46, stars: 0 },
  [NumberCard.NumberCard47]: { color: Colors.Yellow, number: 47, stars: 0 },
  [NumberCard.NumberCard48]: { color: Colors.Green, number: 48, stars: 0 },
  [NumberCard.NumberCard49]: { color: Colors.Cyan, number: 49, stars: 0 },
  [NumberCard.NumberCard50]: { color: Colors.Orange, number: 50, stars: 0 },
  [NumberCard.NumberCard51]: { color: Colors.Pink, number: 51, stars: 2 },
  [NumberCard.NumberCard52]: { color: Colors.Yellow, number: 52, stars: 2 },
  [NumberCard.NumberCard53]: { color: Colors.Green, number: 53, stars: 2 },
  [NumberCard.NumberCard54]: { color: Colors.Cyan, number: 54, stars: 2 },
  [NumberCard.NumberCard55]: { color: Colors.Orange, number: 55, stars: 2 },
  [NumberCard.NumberCard56]: { color: Colors.Pink, number: 56, stars: 0 },
  [NumberCard.NumberCard57]: { color: Colors.Yellow, number: 57, stars: 0 },
  [NumberCard.NumberCard58]: { color: Colors.Green, number: 58, stars: 0 },
  [NumberCard.NumberCard59]: { color: Colors.Cyan, number: 59, stars: 0 },
  [NumberCard.NumberCard60]: { color: Colors.Orange, number: 60, stars: 0 },
  [NumberCard.NumberCard61]: { color: Colors.Pink, number: 61, stars: 1 },
  [NumberCard.NumberCard62]: { color: Colors.Yellow, number: 62, stars: 1 },
  [NumberCard.NumberCard63]: { color: Colors.Green, number: 63, stars: 1 },
  [NumberCard.NumberCard64]: { color: Colors.Cyan, number: 64, stars: 1 },
  [NumberCard.NumberCard65]: { color: Colors.Orange, number: 65, stars: 1 },
  [NumberCard.NumberCard66]: { color: Colors.Pink, number: 66, stars: 0 },
  [NumberCard.NumberCard67]: { color: Colors.Yellow, number: 67, stars: 0 },
  [NumberCard.NumberCard68]: { color: Colors.Green, number: 68, stars: 0 },
  [NumberCard.NumberCard69]: { color: Colors.Cyan, number: 69, stars: 0 },
  [NumberCard.NumberCard70]: { color: Colors.Orange, number: 70, stars: 0 },
  [NumberCard.NumberCard71]: { color: Colors.Pink, number: 71, stars: 2 },
  [NumberCard.NumberCard72]: { color: Colors.Yellow, number: 72, stars: 2 },
  [NumberCard.NumberCard73]: { color: Colors.Green, number: 73, stars: 2 },
  [NumberCard.NumberCard74]: { color: Colors.Cyan, number: 74, stars: 2 },
  [NumberCard.NumberCard75]: { color: Colors.Orange, number: 75, stars: 2 },
  [NumberCard.NumberCard76]: { color: Colors.Pink, number: 76, stars: 0 },
  [NumberCard.NumberCard77]: { color: Colors.Yellow, number: 77, stars: 0 },
  [NumberCard.NumberCard78]: { color: Colors.Green, number: 78, stars: 0 },
  [NumberCard.NumberCard79]: { color: Colors.Cyan, number: 79, stars: 0 },
  [NumberCard.NumberCard80]: { color: Colors.Orange, number: 80, stars: 0 },
  [NumberCard.NumberCard81]: { color: Colors.Pink, number: 81, stars: 1 },
  [NumberCard.NumberCard82]: { color: Colors.Yellow, number: 82, stars: 1 },
  [NumberCard.NumberCard83]: { color: Colors.Green, number: 83, stars: 1 },
  [NumberCard.NumberCard84]: { color: Colors.Cyan, number: 84, stars: 1 },
  [NumberCard.NumberCard85]: { color: Colors.Orange, number: 85, stars: 1 },
  [NumberCard.NumberCard86]: { color: Colors.Pink, number: 86, stars: 0 },
  [NumberCard.NumberCard87]: { color: Colors.Yellow, number: 87, stars: 0 },
  [NumberCard.NumberCard88]: { color: Colors.Green, number: 88, stars: 0 },
  [NumberCard.NumberCard89]: { color: Colors.Cyan, number: 89, stars: 0 },
  [NumberCard.NumberCard90]: { color: Colors.Orange, number: 90, stars: 0 },
}